services:
  db:
    image: postgres:15
    container_name: smart_kitchen_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smart_kitchen_2026
      POSTGRES_DB: smart_kitchen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: